name: main-pipeline

on:
  workflow_dispatch:
    inputs:
      regions_selection:
        type: choice
        description: environment for terraform to deploy
        required: true
        default: northcentralus
        options:
          - northcentralus
          - centralus
          - eastus
      tf_operations:
        type: choice
        description: Terraform operation to perform
        required: true
        default: plan
        options:
          - plan
          - apply
          - destroy
      tf_additional_command_options:
        description: (Optional) CLI options to pass to the OpenTofu Operation
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # PLANING JOB
  tofu_plan:
    permissions:
      contents: 'read'
      pages: write
      id-token: 'write'
    
    env:
      tf_destroy_flag: ${{ inputs.tf_operations == 'destroy' && '-destroy' || '' }}

    runs-on: ubuntu-latest

    outputs:
      plan_exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'secure-way-460121-s4'
          workload_identity_provider: 'projects/481679777603/locations/global/workloadIdentityPools/github-account/providers/github'

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu init
        id: init
        run: tofu init
      
      - name: OpenTofu Validate
        id: Validate
        run: tofu validate

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -out terraform.tfplan -detailed-exitcode -input=false $tf_destroy_flag $tf_additional_command_options
        env:
          TF_WORKSPACE: usncz
          TF_VAR_TAG_AZDO_PROJECT_NAME: main
      
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform.tfplan
  
  # APPROVAL
  manual_approval:
    needs:
      - tofu_plan
    if: needs.tofu_plan.outputs.plan_exitcode == 2 && (inputs.tf_operations == 'apply' || inputs.tf_operations == 'destroy')
    runs-on: ubuntu-latest
    environment:
      name: approval
    
    steps:
      - name: Run a one-line script
        run: echo ${{ needs.tofu_plan.outputs.plan_exitcode }}

  # APPLYING JOBS
  tofu_auto_aprove:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      pages: write
      id-token: 'write'
    needs: 
      - manual_approval
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'secure-way-460121-s4'
          workload_identity_provider: 'projects/481679777603/locations/global/workloadIdentityPools/github-account/providers/github'
      
      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu init
        id: init
        run: tofu init
      
      - name: OpenTofu Validate
        id: Validate
        run: tofu validate

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: OpenTofu Apply
        id: apply
        run: tofu apply -input=false terraform.tfplan
        env:
          TF_WORKSPACE: usncz
          TF_VAR_TAG_AZDO_PROJECT_NAME: main