name: main-pipeline

on:
  workflow_dispatch:
    inputs:
      regions_selection:
        type: choice
        description: environment for terraform to deploy
        required: true
        default: northcentralus
        options:
          - northcentralus
          - centralus
          - eastus
      tf_operations:
        type: choice
        description: Terraform operation to perform
        required: true
        default: plan
        options:
          - plan
          - apply
          - destroy
      tf_additional_command_options:
        description: (Optional) CLI options to pass to the OpenTofu Operation
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tofu_plan:
    permissions:
     contents: 'read'
     pages: write
     id-token: 'write'
    
    env:
      tf_destroy_flag: ${{ github.event.inputs.tf_operation == 'destroy' && '-destroy' || '' }}

    runs-on: ubuntu-latest

    outputs:
      plan_exitcode: steps.plan.outputs.exitcode
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'secure-way-460121-s4'
          workload_identity_provider: 'projects/481679777603/locations/global/workloadIdentityPools/github-account/providers/github'

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu init
        id: init
        run: tofu init
      
      - name: OpenTofu Validate
        id: Validate
        run: tofu validate

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -out terraform.tfplan -detailed-exitcode -input=false $tf_destroy_flag $tf_additional_command_options
        env:
          TF_WORKSPACE: usncz
          TF_VAR_TAG_AZDO_PROJECT_NAME: main
        
      - name: Run a one-line script
        run: echo ${{ steps.plan.outputs.exitcode }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform.tfplan
  
  manual_approval:
    needs:
      - tofu_plan
    if: needs.tofu_plan.plan_exitcode == 0
    runs-on: ubuntu-latest
    environment:
      name: approval

  # tofu_auto_aprove:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - manual_approval
  #   steps:
  #     - name: Run a one-line script
  #       run: echo waiting for project