name: main-pipeline

on:
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tofu_plan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu init
        id: init
        run: tofu init
      
      - name: OpenTofu Validate
        id: Validate
        run: tofu validate

      - name: OpenTofu Plan
        id: plan
        run: tofu play
        continue-on-error: true

  tofu_auto_aprove:
    runs-on: ubuntu-latest
    needs: 
      - tofu_plan
    steps:
      - name: Run a one-line script
        run: echo waiting for project