name: main-pipeline

on:
  workflow_dispatch:
    inputs:
      regions_selection:
        type: choice
        description: environment for terraform to deploy
        required: true
        default: northcentralus
        options:
          - northcentralus
          - centralus
          - eastus
      tf_operation:
        type: choice
        description: Terraform operation to perform
        required: true
        default: plan
        options:
          - plan
          - apply
          - destroy


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tofu_plan:
    permissions:
     contents: 'read'
     pages: write
     id-token: 'write'
    
    env:
      tf_destroy_flag: ${{ github.event.inputs.tf_operation == 'destroy' && '-destroy' || '' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'secure-way-460121-s4'
          workload_identity_provider: 'projects/481679777603/locations/global/workloadIdentityPools/github-account/providers/github'

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu init
        id: init
        run: tofu init
      
      - name: OpenTofu Validate
        id: Validate
        run: tofu validate

      - name: Run a one-line script
        run: echo $env

      - name: OpenTofu Plan
        id: plan
        run: tofu plan
        env:
          TF_WORKSPACE: usncz
          TF_VAR_TAG_AZDO_PROJECT_NAME: main
  
  # manual_approval:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - tofu_plan
  #   environment:
  #     name: approval

  # tofu_auto_aprove:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - manual_approval
  #   steps:
  #     - name: Run a one-line script
  #       run: echo waiting for project